# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
        ('courses_app', '0002_remove_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='join',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='first_app.User'),
        ),
    ]
